# Numpy

#### **What is NumPy?**
NumPy is the fundamental package for scientific computing in Python.
It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
https://numpy.org/devdocs/user/whatisnumpy.html

**What’s the difference between a Python list and a NumPy array?**
- NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.
- The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.
- https://python.plainenglish.io/python-list-vs-numpy-array-whats-the-difference-7308cd4b52f6
- https://www.analyticsvidhya.com/blog/2021/05/why-you-should-avoid-using-python-lists/
- https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.

In [ ]:
list1 = [1, 2, 3, 4, 5 ]

list2 = [7, 8, 9, 10, 5]

print("list1 + list2 = {}".format(list1 + list2))

print("list1 * list2 = {}".format(list1 * 2))

# print("list1 / list2 = {}".format(list1 / 8))

print("list1 - list2 = {}".format(list1 - list2))



In [ ]:
import numpy as np

list1 = [1, 2, 3, 4, 5 ]
arr1 = np.array(list1)

list2 = [7, 8, 9, 10, 5]
arr2 = np.array(list2)

print("arr1 + arr2 = {}".format(arr1 + arr2))

print("arr1 * arr2 = {}".format(arr1 * 2))

print("arr1 / arr2 = {}".format(arr1 / 8))

print("arr1 - arr2 = {}".format(arr1 - arr2))

**Why use NumPy?**

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [ ]:
import sys

print(sys.getsizeof(b))
a = [1, 2, 3, 4, 5]
print(sys.getsizeof(a))
print(a[0].__sizeof__() * len(a))

## Installing Numpy

In [ ]:
 #pip install numpy

## Calling Numpy

**How to import NumPy?**
- To access NumPy and its functions import it in your Python code like this:

In [ ]:
import numpy as np

**What is an array?**

- An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

- An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.


https://numpy.org/devdocs/user/absolute_beginners.html#whats-the-difference-between-a-python-list-and-a-numpy-array

In [ ]:
# One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("A is : \n", a, a.shape, a.size)
print("B is : \n", b, b.shape, b.size)

***We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.***

In [ ]:
print(b[0])

***More information about arrays***

- This section covers 1D array, 2D array, ndarray, vector, matrix

- You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

***What are the attributes of an array?***

- An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

- In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

 [[0., 0., 0.],
  [1., 1., 1.]]

- Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

- Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array.

- Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array, you can often access an array through its attributes.


***How to create a basic array***
- This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

***To create a NumPy array, you can use the function np.array().***

- All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
a[1]

***A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:***

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(type(x))
# <class 'numpy.ndarray'>
print(x.shape)
# (2, 3)
print(x.dtype)
# dtype('int32')
print(x)
print(x.sum(axis=1))

***you can easily create an array filled with 0’s:***

In [ ]:
np.zeros(2)

In [ ]:
np.zeros((2,2), dtype=float)

***you can easily create an array filled with 1’s:***

In [ ]:
np.ones(2)
# array([1., 1.])

In [ ]:
np.ones((2,2), dtype=float)

***The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!***

In [ ]:
# Create an empty array with 2 elements
np.empty(2)
# array([3.14, 42.  ])  # may vary

***You can create an array with arange of elements:***

In [ ]:
np.arange(4)
# array([0, 1, 2, 3])

***And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.***

In [ ]:
# np.arange([start,] stop[, step,], dtype=None)
np.arange(2, 9, 2, float)
# array([2, 4, 6, 8])

In [ ]:
data = np.array([1, 2, 3])
data.shape

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.flatten()

***You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:***

In [ ]:
np.linspace(0, 10, num=5)
# array([ 0. ,  2.5,  5. ,  7.5, 10. ])

***Specifying your data type***

***While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.***


In [ ]:
x = np.ones(2, dtype=np.int64)
x
# array([1, 1])

***Adding, removing, and sorting elements***
- This section covers np.sort(), np.concatenate()
- Sorting an element is simple with np.sort().
- You can specify the axis, kind, and order when you call the function.

- If you start with this array:

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
# You can quickly sort the numbers in ascending order with:
np.sort(arr)[::-1]
# array([1, 2, 3, 4, 5, 6, 7, 8])

***You can concatenate them with np.concatenate().***

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate([a,b])
# array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(x, "\n\n", y)
np.concatenate((x, y), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

***How do you know the shape and size of an array?***
- This section covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`

- `ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

- `ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

- `ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

  - For example, if you create this array:

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
print(array_example)
array_example.sum(axis=2)

***To find the number of dimensions of the array, run:***

In [ ]:
array_example.ndim

***To find the total number of elements in the array, run:***

In [ ]:
array_example.size

***And to find the shape of your array, run:***

In [ ]:
array_example.shape


***Can you reshape an array?***
- This section covers arr.reshape()
- Using arr.reshape() will give a new shape to an array without changing the data.
- Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array.
- If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

- If you start with this array:


In [ ]:
a = np.arange(6)
print(a)
# [0 1 2 3 4 5]

# You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns:

b = a.reshape(3, 2)
print(b)
# [[0 1]
#  [2 3]
#  [4 5]]

***How to convert a 1D array into a 2D array (how to add a new axis to an array)***
- This section covers np.newaxis, np.expand_dims

- You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

- Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

- For example, if you start with this array:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
# (6,)

In [ ]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis, :]
print(a2.shape)
# (1, 6)
print(a2)

***You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis.***
- For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape
# (1, 6)

***Or, for a column vector, you can insert an axis along the second dimension:***

In [ ]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)
# (6, 1)

In [ ]:
a[np.newaxis,np.newaxis]

***You can also expand an array by inserting a new axis at a specified position with np.expand_dims.***
- For example, if you start with this array:


In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape) # (6,)
print(a.ndim)
print(a)

(6,)
1
[1 2 3 4 5 6]


***You can use np.expand_dims to add an axis at index position 1 with:***

In [4]:
b = np.expand_dims(a, axis=1)
print(b.shape) # (6,1)
print(b.ndim)
print(b)

(6, 1)
2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


***You can add an axis at index position 0 with:***

In [5]:
c = np.expand_dims(a, axis=0)
print(c.shape) #(1, 6)
print(c.ndim)
print(c)

(1, 6)
2
[[1 2 3 4 5 6]]


### Indexing and slicing

***You can index and slice NumPy arrays in the same ways you can slice Python lists.***

<img src=https://numpy.org/devdocs/_images/np_indexing.png width=1000>

In [6]:
data = np.array([1, 2, 3, 4, 5, 6])

print(data[1]) # 2
print(data[0:2]) # array([1, 2])
print(data[1:]) #array([2, 3])
print(data[-2:]) #array([2, 3])

2
[1 2]
[2 3 4 5 6]
[5 6]


In [7]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(a[a < 5])

[1 2 3 4]


In [10]:
five_up = (a >= 5)
print(five_up)
print(a[five_up])
# [ 5  6  7  8  9 10 11 12]

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


In [11]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
# [ 2  4  6  8 10 12]

[ 2  4  6  8 10 12]


In [12]:
five_up = (a > 5) | (a == 5)
print(five_up)
# [[False False False False]
#  [ True  True  True  True]
#  [ True  True  True True]]
print(a[five_up])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


In [36]:
a = np.arange(10)
print(a)
even = (a % 2 == 0)
print(even)
greater = (a[even] > 5)
print(greater)
a[even][greater]
np.nonzero(a%2==0)

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[False False False  True  True]


(array([0, 2, 4, 6, 8], dtype=int64),)

***You can also use np.nonzero() to select elements or indices from an array.***

- Starting with this array:

In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

***You can use np.nonzero() to print the indices of elements that are, for example, less than 5:***

In [25]:
b = np.nonzero(a < 5)
print(b)
# (array([0, 0, 0, 0]), array([0, 1, 2, 3]))

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


***In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.***

- If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [37]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)
# (0, 0)
# (0, 1)
# (0, 2)
# (0, 3)


(0, 0)
(0, 1)
(0, 2)
(0, 3)


***You can also use np.nonzero() to print the elements in an array that are less than 5 with:***

In [41]:
print(a[b])
# [1 2 3 4]

[1 2 3 4]


***If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:***

In [42]:
not_there = np.nonzero(a == 42)
print(not_there)
# (array([], dtype=int64), array([], dtype=int64))

(array([], dtype=int64), array([], dtype=int64))


***Using the copy method will make a complete copy of the array and its data (a deep copy).***
- To use this on your array, you could run:

In [43]:
b2 = a.copy()
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations
***This section covers addition, subtraction, multiplication, division, and more***
- once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”
<img src=https://numpy.org/devdocs/_images/np_array_dataones.png width=1000>

In [44]:
# You can add the arrays together with the plus sign.

data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones
# array([2, 3])

array([2, 3])

<img src=https://numpy.org/devdocs/_images/np_data_plus_ones.png  width=1000>

***You can, of course, do more than just addition!***

<img src=https://numpy.org/devdocs/_images/np_sub_mult_divide.png  width=1000>

In [45]:
print(data - ones) # array([0, 1])
print(data * data) # array([1, 4])
print(data / data) # array([1., 1.])

[0 1]
[1 4]
[1. 1.]


***Basic operations are simple with NumPy.***
- If you want to find the sum of the elements in an array, you’d use sum().
- This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [46]:
a = np.array([1, 2, 3, 4])

a.sum()
# 10

10

***To add the rows or the columns in a 2D array, you would specify the axis.***

- If you start with this array:

In [47]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

***You can sum over the axis of rows with:***

In [48]:
b.sum(axis=0)
# array([3, 3])

array([3, 3])

***You can sum over the axis of columns with:***

In [49]:
b.sum(axis=1)
# array([2, 4])

array([2, 4])

## Broadcasting
<img src=https://numpy.org/devdocs/_images/np_multiply_broadcasting.png  width=1000>


- There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes.
- For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers.
- You can perform this operation with:

In [50]:
data = np.array([1.0, 2.0])
data * 1.6
# array([1.6, 3.2])

array([1.6, 3.2])

- NumPy understands that the multiplication should happen with each cell.
- That concept is called `broadcasting`. `Broadcasting` is a mechanism that allows NumPy to perform operations on arrays of different shapes.
- The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1.
- If the dimensions are not compatible, you will get a ValueError.

In [51]:
data1 = np.array([1.0, 2.0])
data2 = np.array([1.0, 2.0, 3.0])
data1 * data2

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

***This section covers maximum, minimum, sum, mean, product, standard deviation, and more***
- NumPy also performs aggregation functions.
- In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

<img src=https://numpy.org/devdocs/_images/np_aggregation.png  width=1000>

In [56]:
print(data)
print(data.max()) # 2.0
print(data.min()) # 1.0
print(data.sum()) # 3.0
print(data.mean())
print(data.std())

[1. 2.]
2.0
1.0
3.0
1.5
0.5


In [64]:
data = np.array([1,1,2,2])
print(data.mean())
print(data.std())

1.5
0.5


In [65]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [67]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [ ]:
a.sum()
# 4.8595784

In [ ]:
a.min()
# 0.05093587

In [66]:
a.min(axis=0)
# array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

### Creating matrices

***You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.***
<img src=https://numpy.org/devdocs/_images/np_create_matrix.png width= 1000>

In [1]:
import numpy as np
data = np.array([[1, 2], [3, 4], [5, 6]])
data
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

****Indexing and slicing operations are useful when you’re manipulating matrices:***
<img src = https://numpy.org/devdocs/_images/np_matrix_indexing.png width = 1000>

In [3]:
print(data[0, 1]) # 2
print(data[1:3,:]) # array([[3, 4],[5, 6]])
print(data[0:2, 0]) # array([1, 3])

2
[[3 4]
 [5 6]]
[1 3]


***You can aggregate matrices the same way you aggregated vectors:***
<img src =https://numpy.org/devdocs/_images/np_matrix_aggregation.png width = 1000>

In [4]:
print(data.max()) # 6
print(data.min()) # 1
print(data.sum())# 21

6
1
21


***You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter. To illustrate this point, let’s look at a slightly modified dataset:***
<img src = https://numpy.org/devdocs/_images/np_matrix_aggregation_row.png width = 1000 >    

In [5]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
# array([[1, 2],
#        [5, 3],
#        [4, 6]])
print(data.max(axis=0)) # array([5, 6])
print(data.max(axis=1)) # array([2, 5, 6])

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


***once you’ve created your matrices, you can add and multiply them using arithmetic operators if you have two matrices that are the same size.***
<img src =https://numpy.org/devdocs/_images/np_matrix_arithmetic.png  width = 1000>

In [6]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones
# array([[2, 3],
#        [4, 5]])

array([[2, 3],
       [4, 5]])

***You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation.***
<img src =https://numpy.org/devdocs/_images/np_matrix_broadcasting.png  width = 1000>

In [7]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row
# array([[2, 3],
#        [4, 5],
#        [6, 7]])

array([[2, 3],
       [4, 5],
       [6, 7]])

***There are often instances where we want NumPy to initialize the values of an array.***
- NumPy offers functions like `ones()` and `zeros()`, and the `random`.Generator class for random number generation for that.
- All you need to do is pass in the number of elements you want it to generate:
<img src =  https://numpy.org/devdocs/_images/np_ones_zeros_random.png width = 1000>

In [ ]:
print(np.ones(3)) # array([1., 1., 1.])
print(np.zeros(3)) # array([0., 0., 0.])
print(np.random.random(3)) # array([0.63696169, 0.26978671, 0.04097352])

***You can also use `ones()`, `zeros()`, and `random()` to create a 2D array if you give them a tuple describing the dimensions of the matrix:***
<img src = https://numpy.org/devdocs/_images/np_ones_zeros_matrix.png  width = 1000>

In [ ]:
print(np.ones((3, 2)))
# array([[1., 1.],
#        [1., 1.],
#        [1., 1.]])
print(np.zeros((3, 2)))
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.]])
print(np.random.random((3, 2)))
# array([[0.01652764, 0.81327024],
#        [0.91275558, 0.60663578],
#        [0.72949656, 0.54362499]])  # may vary

### Generating random numbers
- The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.
- You can generate a 2 x 4 array of random integers between 0 and 4 with:

In [8]:
np.random.randint(10, size=(2, 4))
# array([[2, 1, 1, 0],
#        [0, 0, 0, 4]])  # may vary

array([[6, 2, 1, 4],
       [7, 6, 2, 2]])

***How to get unique items and counts***

- This section covers `np.unique()`

- You can find the unique elements in an array easily with np.unique.

- For example, if you start with this array:

In [12]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(a)

# you can use np.unique to print the unique values in your array:

unique_values = np.unique(a)
print(unique_values)
# [11 12 13 14 15 16 17 18 19 20]
np.unique(a).size

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


10

In [44]:
np.sort(np.unique(np.random.randint(0,100,size=(100)), return_counts=True, return_index=True))

array([[ 0,  1,  2,  4,  5,  6,  8,  9, 10, 11, 17, 18, 19, 20, 21, 23,
        25, 26, 27, 31, 34, 36, 37, 38, 40, 41, 46, 47, 49, 50, 52, 53,
        54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 66, 67, 70, 71, 72, 73,
        74, 75, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87, 89, 94, 95, 97,
        98, 99],
       [ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 16, 17, 18,
        19, 20, 22, 24, 25, 26, 27, 28, 29, 30, 31, 35, 36, 37, 38, 43,
        46, 48, 50, 51, 52, 53, 54, 56, 57, 58, 59, 60, 61, 62, 64, 65,
        67, 68, 70, 72, 73, 74, 80, 81, 82, 83, 85, 88, 90, 91, 93, 95,
        98, 99],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  4,
         4,  6]], dtype=int64)

***To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the return_index argument in np.unique() as well as your array.***

In [36]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list, unique_values)
# [ 0  2  3  4  5  6  7 12 13 14]

[ 0  2  3  4  5  6  7 12 13 14] [11 12 13 14 15 16 17 18 19 20]


***You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.***

In [37]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(unique_values, occurrence_count)
# [3 2 2 2 1 1 1 1 1 1]

[11 12 13 14 15 16 17 18 19 20] [3 2 2 2 1 1 1 1 1 1]


***This also works with 2D arrays! If you start with this array:***

In [45]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

***You can find unique values with:***
 - If the axis argument isn’t passed, your 2D array will be flattened.

In [46]:
unique_values = np.unique(a_2d)
print(unique_values)
# [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


***If you want to get the unique rows or columns, make sure to pass the axis argument.***
- To find the unique rows, specify axis=0 and for columns, specify axis=1.

In [47]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


***To get the unique rows, index position, and occurrence count, you can use:***

In [ ]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
print(indices)
# [0 1 2]
print(occurrence_count)
# [2 1 1]

### Transposing and reshaping a matrix
- This section covers arr.reshape(), arr.transpose(), arr.T

- It’s common to need to transpose your matrices.
- NumPy arrays have the property T that allows you to transpose a matrix.

<img src =https://numpy.org/devdocs/_images/np_transposing_reshaping.png  width = 1000>

***If you start with this array:***

In [48]:
arr = np.arange(6).reshape((2, 3))
arr
# array([[0, 1, 2],
#        [3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

***You can transpose your array with arr.transpose().***

In [49]:
arr.transpose()
# array([[0, 3],
#        [1, 4],
#        [2, 5]])

array([[0, 3],
       [1, 4],
       [2, 5]])

***You can also use arr.T:***

In [ ]:
arr.T
# array([[0, 3],
#        [1, 4],
#        [2, 5]])

### How to reverse an array
- This section covers np.flip()

- NumPy’s `np.flip()` function allows you to flip, or reverse, the contents of an array along an axis.
- When using `np.flip()`, specify the array you would like to reverse and the axis.
- If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.

- Reversing a 1D array

- If you begin with a 1D array like this one:

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

***You can reverse it with:***

In [51]:
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)
# If you want to print your reversed array, you can run:
# Reversed Array:  [8 7 6 5 4 3 2 1]

Reversed Array:  [8 7 6 5 4 3 2 1]


**

***Reversing a 2D array***

- A 2D array works much the same way.

- If you start with this array:

In [52]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

***You can reverse the content in all of the rows and all of the columns with:***

In [53]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)
# [[12 11 10  9]
#  [ 8  7  6  5]
#  [ 4  3  2  1]]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


***You can easily reverse only the rows with:***

In [54]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)
# [[ 9 10 11 12]
#  [ 5  6  7  8]
#  [ 1  2  3  4]]

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


***Or reverse only the columns with:***

In [55]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)
# [[ 4  3  2  1]
#  [ 8  7  6  5]
#  [12 11 10  9]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [61]:
print(arr_2d)
arr_2d.sum(axis=1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([10, 26, 42])

***You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row):***

In [62]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)
# [[ 1  2  3  4]
#  [ 8  7  6  5]
#  [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


***You can also reverse the column at index position 1 (the second column):***

In [63]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)
# [[ 1 10  3  4]
#  [ 8  7  6  5]
#  [ 9  2 11 12]]

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


### Reshaping and flattening multidimensional arrays

- This section covers .flatten(), ravel()

- There are two popular ways to flatten an array: `.flatten()` and `.ravel()`.
- The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”).
- This means that any changes to the new array will affect the parent array as well.
- Since ravel does not create a copy, it’s memory efficient.

- If you start with this array:

In [64]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

***You can use flatten to flatten your array into a 1D array.***

In [65]:
x.flatten()
# array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

***When you use flatten, changes to your new array won’t change the parent array.***

- For example:

In [66]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
print(a1)  # New array
# [99  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


***But when you use ravel, the changes you make to the new array will affect the parent array.***

- For example:

In [67]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
# [[98  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
print(a2)  # New array
# [98  2  3  4  5  6  7  8  9 10 11 12]

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


In [107]:
# my_arr = np.arange(start=1, stop=10).reshape((3, 3))
import string
my_arr = np.array([*string.digits][1:], dtype=str).reshape(3,3)
my_arr2 = np.ravel(my_arr)
my_arr2[1] = "X"
print(my_arr)
print(my_arr2)

[['1' 'X' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
['1' 'X' '3' '4' '5' '6' '7' '8' '9']


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

### Working with mathematical formulas
- The ease of implementing mathematical formulas that work on arrays is one of the things that make NumPy so widely used in the scientific Python community.

- For example, this is the mean square error formula (a central formula used in supervised machine learning models that deal with regression):
<img src = https://numpy.org/devdocs/_images/np_MSE_formula.png width =1000>

***Implementing this formula is simple and straightforward in NumPy:***
<img src = https://numpy.org/devdocs/_images/np_MSE_implementation.png width = 1000>

***What makes this work so well is that predictions and labels can contain one or a thousand values. They only need to be the same size.***

- You can visualize it this way:
<img src = https://numpy.org/devdocs/_images/np_mse_viz1.png width=1000>

***In this example, both the predictions and labels vectors contain three values, meaning n has a value of three.***
- After we carry out subtractions the values in the vector are squared. Then NumPy sums the values, and your result is the error value for that prediction and a score for the quality of the model.

<img src = https://numpy.org/devdocs/_images/np_mse_viz2.png width = 1000>
    

<img src = https://numpy.org/devdocs/_images/np_MSE_explanation2.png width = 1000>


### eye
***Creates an identity matrix***

In [108]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
***Numpy also has lots of ways to create random number arrays:***

### rand
***Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).***

In [109]:
np.random.rand(2)

array([0.0549156 , 0.71602054])

In [110]:
np.random.rand(5,5)

array([[0.80884135, 0.44115341, 0.74377558, 0.69511012, 0.09869225],
       [0.44183884, 0.83183973, 0.54542619, 0.30635568, 0.89875764],
       [0.25723339, 0.6390784 , 0.85458265, 0.52895625, 0.25746383],
       [0.13021165, 0.50907957, 0.58714256, 0.35439961, 0.16606563],
       [0.59158838, 0.83757644, 0.13784292, 0.88252506, 0.7312295 ]])

### randn
***Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:***

In [111]:
np.random.randn(1)

array([-0.69644542])

In [ ]:
np.random.randn(5,5)

### randint
***Return random integers from low (inclusive) to high (exclusive).***

In [ ]:
np.random.randint(1,100)

In [ ]:
np.random.randint(0,100,10)

### argmax
***Returns the indices of the maximum values along an axis.***

In [117]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 80], [9, 10, 11, 0]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 80],
       [ 9, 10, 11,  0]])

In [116]:
x.argmax()

7

### argmin
***Returns the indices of the minimum values along an axis.***

In [118]:
x.argmin()

11